name: Android Build and Deployment Pipeline # optional

on: # on [Events]
  # always push on developer's dev branch after then we do PR into feature from dev,
  # and then PR into release from feature, and then PR into master from release
  push:
    branches: [ 'dev/*/*' ]
  pull_request:
    branches: [ 'release/*', 'feature/*' ]

jobs: # groups
  Android-CI_CD: # job name, any name. Give proper name
    runs-on: ubuntu-latest # runs-on: Runner
    steps: # keyword name
      # follows these steps on order
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1

      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Echo current branch
        run: echo ${{ steps.extract_branch.outputs.branch }}

      - name: Setup Source (checkout etc.)
        uses: actions/checkout@v3 # uses: actions/actual_action
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # I could also simply run ./gradlew check here instead of using already published github actions
      # but Cloud based CI/CD like github actions don't prefer our implementation
      - name: Checkstyle
        uses: dbelyaev/action-checkstyle@v0.7.4
        with:
          workdir: config/checkstyle
          config_file: checkstyle.xml
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          locale: "US"
          reviewdog_flags: -filter-mode=file -fail-on-error

      - name: PMD
        uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '6.40.0'
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1

#      - name: Checkstyle Using Gradlew check
#        run: ./gradlew check

      - name: is Release?
        run: echo ${{ steps.extract_branch.outputs.branch == 'release/*' }}

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew agemodule:testDebugUnitTest &&./gradlew test

      # Build Apks
      - name: Build and Generate Release Apk
        if: ${{ steps.extract_branch.outputs.branch == 'release/*' }}
        run: ./gradlew app:assembleRelease --stacktrace

      - name: Build and Generate EnterpriseQa Apk
        if: ${{ steps.extract_branch.outputs.branch == 'release/*' }}
        run: ./gradlew app:assembleEnterpriseQa --stacktrace

      - name: Build and Generate Debug Apk
        if: ${{ steps.extract_branch.outputs.branch == 'feature/*' }}
        run: ./gradlew app:assembleDebug --stacktrace

