name: learn-github-actions # optional
run-name: ${{ github.actor }} is learning GitHub Actions # optional
on: [push] # on [Events]
jobs: # groups
  check-bats-version: # any name
    runs-on: ubuntu-latest # runs-on: Runner
    steps: # keyword name
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
